apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-api
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: login-api
  template:
    metadata:
      labels:
        app: login-api
    spec:
      containers:
        - name: login-api
          image: 021558411440.dkr.ecr.ap-south-1.amazonaws.com/syndtrak/login-api:latest
          ports:
            - containerPort: 3000
          env:
            - name: PORT
              value: "3000"
            - name: JWT_SECRET
              value: "syndtrak-jwt-secret-2024"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 250m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 20
